spring:
  application:
    name: ai-code-backend
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi com/carlos/aicodebackend
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.carlos.aicodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
